### PR TITLE
Provide minimal test target

### PR DESCRIPTION
**Pull request by AMDmi3**
This at least checks that all imports are satisfied

### CODE REVIEW

**Comment by jarun** [comment]
Thanks for the PR. Unfortunately, CI fails. Please check.

**Comment by jarun** [comment]
It seems the problem is the missing requests module. But, I wonder why would we even need this when we don't have any plans to test `ddgr` on Travis.

**Comment by jarun** [comment]
Yep, it's a good idea to ensure we have the deps. I missed the `requests` library everywhere, for instance.

**Comment by jarun** [comment]
Thank you!

**Comment by AMDmi3** [comment]
Thanks! Just wanted to mention that I've needed this for FreeBSD port, to be able to at least make sure that dependency list is complete and the program is usable. On travis flake8 checks the syntax somewhat so running `ddgr` doesn't seem necessary at first, but I don't think it catches all possible problems since it didn't show problems even without requests module installed.

And also FYI, I've added a FreeBSD port. See https://repology.org/metapackage/ddgr/versions.

**Comment by jarun** [comment]
@asergi it would be good to have Void Linux on the list.

**Comment by AMDmi3** [comment]
We're working on Void linux support repology/repology#400

**Comment by jarun** [comment]
Awesome!

**Pull request merged**
