### PR TITLE
Add Fedora to list of package manager option

### PR DESCRIPTION
**Pull request by eclipseo**
ddgr is now packaged in Fedora 26 and above

### CODE REVIEW

**Comment by jarun** [comment]
Hi @eclipseo, here's a list of some of my other projects which you can consider out for packaging on Fedora:

- [googler](https://github.com/jarun/googler)
- [Buku](https://github.com/jarun/Buku)
- [imgp](https://github.com/jarun/imgp)
- [nnn](https://github.com/jarun/nnn)
- [bcal](https://github.com/jarun/bcal)
- [pdd](https://github.com/jarun/pdd)

All of these are accepted on Debian and Ubuntu families. It would be great if Fedora users can have ready access to these utilities. In fact I am one of those users (at office ;)).

**Comment by jarun** [comment]
@eclipseo did you notice my request above?

**Comment by eclipseo** [comment]
Yes, I'll see what I can do when I have the time.

**Comment by jarun** [comment]
Thank you!

**Comment by eclipseo** [comment]
Packages are done and are now waiting for review:

 - Review Request: googler - Google Search, Google Site Search, Google News
                   from the terminal (Python)
                   https://bugzilla.redhat.com/show_bug.cgi?id=1548764
 - Review Request: buku - Powerful command-line bookmark manager (Python)
                   https://bugzilla.redhat.com/show_bug.cgi?id=1548763
 - Review Request: imgp - Multi-core batch image resizer and rotator (Python)
                   https://bugzilla.redhat.com/show_bug.cgi?id=1548762
 - Review Request: nnn - The missing terminal file browser for X (C)
                   https://bugzilla.redhat.com/show_bug.cgi?id=1548761
 - Review Request: pdd - Tiny date, time diff calculator (Python)
                   https://bugzilla.redhat.com/show_bug.cgi?id=1548760
 - Review Request: bcal - Storage conversion and expression calculator (C)
                   https://bugzilla.redhat.com/show_bug.cgi?id=1548759

**Comment by jarun** [comment]
Thank you so much!

**Pull request merged**
