### PR TITLE
Add --exit option

### PR DESCRIPTION
**Pull request by PaperMountainStudio**
Add option to exit after first search.

### CODE REVIEW

**Comment by jarun** [comment]
We already have it:

    --np, --noprompt      perform search and exit, do not prompt

**Comment by PaperMountainStudio** [comment]
Yes, but it does not offer interactive prompt if I remember correctly.

**Comment by jarun** [comment]
> does not offer interactive prompt

If you have the interactive prompt you can press `q` and exit. It seems like a overkill to have an option just for that.

**Comment by PaperMountainStudio** [comment]
I made this change for usage in my script. So it's up to you whether to merge it.

**Comment by jarun** [comment]
Ahh OK, I get it. I would request you to have a fork. I don't see `ddgr` going through too many changes in the future so it wouldn't be very difficult to merge.

**Pull request closed without merging**
